### ISSUE TITLE
Date Picker Functionality Not Working for Time

### ISSUE THREAD

**Issue by robgnyc** [bonny/WordPress-Simple-Fields#105]
The date picker functionality works fine for date only but if you choose time and date or time only there is nowhere to enter the time, only the date.

![screen shot 2014-04-24 at 3 33 56 pm](https://cloud.githubusercontent.com/assets/6354846/2794012/93e87566-cbe7-11e3-847b-e3f7a1cdbde7.PNG)
![screen shot 2014-04-24 at 3 34 48 pm](https://cloud.githubusercontent.com/assets/6354846/2794016/9cdfc480-cbe7-11e3-8bb9-f38370f8a5dd.PNG)

**Comment by bonny** [comment]
Perhaps due to this error I get using latest Query Monitor:

Broken Dependencies	jquery-timepicker
http://logosack-wp.ep/assets/plugins/simple-fields/js/jquery-ui-timepicker-addon.css	jquery-ui-smoothness (missing)

**Comment by peter-nl** [comment]
It seems Simple Fields v1.4.10 needs some tweaking as for the Date&Timepicker. Maybe this will help some.

The qMonitor's 'broken dependencies warning' is caused by the enqueue depency as specified in field_date_v2.php: 
`wp_enqueue_style("jquery-timepicker", SIMPLE_FIELDS_URL . "js/jquery-ui-timepicker-addon.css", array("jquery-ui-smoothness") );`

Due to the missing css the Timepicker display is somewhat messy but doesn't seem to do much more harm in my simple test set-up.

If is set the timepicker to only date or only time, everything works as expected.
When I select 'Show picker as both date and time', however, I get a script error 'Uncaught TypeError: $.datepicker.log is not a function'. Apparently that function was removed at some point from jQuery UI, ref https://github.com/trentrichardson/jQuery-Timepicker-Addon/issues/545.

Kind regards,
Peter

**Comment by bonny** [comment]
thanks peter. i will release an update soon with this fix.
